# Generated by Django 4.2.16 on 2024-10-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
