# Generated by Django 4.2.16 on 2024-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driverprofile_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
