# Generated by Django 5.1.2 on 2024-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driverprofile_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
