# Generated by Django 5.1.2 on 2024-10-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driverprofile_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
