# Generated by Django 5.1.2 on 2024-10-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driverprofile_end_time_driverprofile_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='start_time',
        ),
    ]
