# Generated by Django 5.1.2 on 2024-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_date_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route_to_pickup', 'En Route to Pickup'), ('goods_collected', 'Goods Collected'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
